# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\u1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from   PyQt5.QtWidgets import *
from   PyQt5.QtGui     import *
from   PyQt5.QtCore    import *
import random

s="BOT:Hello, What is your question for me?\n"



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 720)
        MainWindow.setStyleSheet("#centralwidget{background-color:black;}\n"
".QLabel{color:White;}\n"
"#pushButton{background-color:cyan;border-radius:30}\n"
"\n"
"#pushButton_2{background-color:cyan;border-radius:30}\n"
"\n"
"#pushButton_3{background-color:white;border-radius:30;border:15}\n"

"\n"
".QComboBox{border-radius:10}\n"
"\n"
".QTextEdit{background-color:rgba(0, 0, 255, 0.3);color:white;}\n"
"\n"
".comboBox{color:red}")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        
        #=---------
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(0, -230, 0, 0))
        self.label2.setMinimumSize(QtCore.QSize(1280,1280))
        self.label2.setMaximumSize(QtCore.QSize(1280,1280))
        self.label2.setObjectName("label2")
        
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.movie1 = QMovie("wallpaper2.gif")
        self.movie1.setScaledSize(QSize().scaled(1100,1100, Qt.KeepAspectRatio))
        self.label2.setMovie(self.movie1)
        self.movie1.start()
        #=---------
        
        
        
        
        
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 580, 121, 101))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather/mic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 20, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 110, 1041, 441))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        
        
        #=---------
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(970, 50, 0, 0))
        self.label1.setMinimumSize(QtCore.QSize(170, 170))
        self.label1.setMaximumSize(QtCore.QSize(170, 170))
        self.label1.setObjectName("label")
        
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.movie2 = QMovie("robot1.gif")
        self.movie2.setScaledSize(QSize().scaled(150, 150, Qt.KeepAspectRatio))
        self.label1.setMovie(self.movie2)
        self.movie2.start()
        #=---------
        
        
        
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        global s
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "REC"))
        self.label.setText(_translate("MainWindow", "WELCOME USER!"))
        self.textEdit.setText(s)
        
        self.pushButton.clicked.connect(self.click)

    def click(self):
        global s
        s=s+"\nBOT:you have clicked"
        self.textEdit.setText(s)
        
        self.label1.setGeometry(QtCore.QRect(955, 35, 0, 0))
        
        n=random.randint(2,4)
        
        self.movie2 = QMovie("robot"+str(n)+".gif")
        self.movie2.setScaledSize(QSize().scaled(190, 190, Qt.KeepAspectRatio))
        self.label1.setMovie(self.movie2)
        self.movie2.start()
        
                
import resource_rc




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
